In [1]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow.keras import layers
from keras.regularizers import L1L2

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt
import os
import pathlib
import PIL
import PIL.Image
import pickle
import time
import seaborn

In [2]:
data_path = tf.keras.utils.get_file(
    "anuka1200",
    "https://github.com/raquelhortab/stackoverflow/raw/main/anuka1200.tar.gz",
    untar=True)
a_folder = "Tipo A: Kunzea"
b_folder = "Tipo B: Lepto"
data_dir = pathlib.Path(data_path) 
len(list(data_dir.glob('*/*.png')))

2400

In [3]:
batch_size = 32
img_height = 180
img_width = 180
image_size = (180,180)

In [4]:
train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    data_path,
    label_mode='categorical',
    validation_split=0.2,
    subset="training",
    seed=1337,
    image_size=image_size,
    batch_size=batch_size,
)
test_ds = tf.keras.preprocessing.image_dataset_from_directory(
    data_path,
    label_mode='categorical',
    validation_split=0.2,
    subset="validation",
    seed=1337,
    image_size=image_size,
    batch_size=batch_size,
)


Found 2400 files belonging to 2 classes.
Using 1920 files for training.
Found 2400 files belonging to 2 classes.
Using 480 files for validation.


In [5]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=(img_width, img_height,3)))
model.add(tf.keras.layers.experimental.preprocessing.Rescaling(1./255))
model.add(tf.keras.layers.Dense(2, activation=tf.keras.activations.softmax))
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss=tf.keras.losses.categorical_crossentropy,
              metrics=['accuracy'])
model.build()
model.summary()
model.fit(train_ds, validation_data=test_ds, epochs=20)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 97200)             0         
_________________________________________________________________
rescaling (Rescaling)        (None, 97200)             0         
_________________________________________________________________
dense (Dense)                (None, 2)                 194402    
Total params: 194,402
Trainable params: 194,402
Non-trainable params: 0
_________________________________________________________________
Epoch 1/20
60/60 [==============================] - 5s 65ms/step - loss: 0.6363 - accuracy: 0.7642 - val_loss: 0.5352 - val_accuracy: 0.8188
Epoch 2/20
60/60 [==============================] - 4s 58ms/step - loss: 0.3745 - accuracy: 0.8513 - val_loss: 0.5725 - val_accuracy: 0.8458
Epoch 3/20
60/60 [==============================] - 4s 60ms/step - loss: 0.3588 - accuracy: 0.8730

In [6]:
model.predict(test_ds)[0]

array([0.10411204, 0.89588803], dtype=float32)

In [7]:
model.predict(test_ds)[0]

array([0.83601135, 0.16398862], dtype=float32)

In [8]:
model.predict(test_ds)[0]

array([0.9331869, 0.0668131], dtype=float32)

In [9]:
model.predict(test_ds)[0]

array([2.8840926e-18, 1.0000000e+00], dtype=float32)

In [10]:
model.predict(test_ds)[0]

array([0.9972692 , 0.00273071], dtype=float32)

In [11]:
model.predict(test_ds)[0]

array([1.2084037e-12, 1.0000000e+00], dtype=float32)

In [12]:
model.predict(test_ds)[0]

array([1.6487637e-04, 9.9983513e-01], dtype=float32)